language:
- objective-c # use OS X workers
notifications:
  email:
    on_success: never
    on_failure: always
install:
    - brew install python
    - brew link --overwrite python
    - pip install nose macholib
script:
    - nosetests
